### ISSUE TITLE
Not using previously computed Freesurfer outputs (Freesurfer version too new?)

### ISSUE THREAD

**Issue by bwinsto2** [bids-apps/baracus#29]
Hi. Using the following command:
`docker run -ti --rm \
-v /data/adam_music/raw_data:/data/in \
-v /data/adam_music/derivatives/freesurfer:/data/freesurfer \
-v /data/adam_music/derivatives/baracus:/data/out \
bids/baracus /data/in /data/out participant \
--license_key "XX" --freesurfer_dir /data/freesurfer --participant_label P01`

And it's saying Freesurfer data not found for P01. I previously ran fMRIprep on these subjects and Freesurfer outputs are there in derivatives/freesurfer. Actually, it started to run recon-all in the exact same directory where the other outputs are...lol. 

The docs mention Freesurfer 5.3.0. Mine are in a newer version: 7.3.2. Could this be the problem? I could re-run recon-all, but this would be cumbersome, and I'm also on a deadline.

Any help is appreciated! Thanks.

**Comment by JavierSanchez3** [comment]
Hello. I got an error when trying to execute the commands to obtain the predicted brain age. I previously processed the data with FreeSurfer v7.4.0, but an error about "shape does not look right: (1, 58)" appeared. When I processed the data with FreeSurfer v5.3 using Baracus, everything was fine. 

My question is whether it is possible to adjust something to run Baracus using the processed FreeSurfer data with the latest version in order to avoid re-processing the images.

Thanks!



"FINISHED. Prepared sub-103_ses-1 sub-103_ses-6
Traceback (most recent call last):
  File "/usr/local/anaconda/bin/run_brain_age_bids.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/code/scripts/run_brain_age_bids.py", line 83, in <module>
    predict_brain_age_single_subject(**d)
  File "/code/baracus/predict.py", line 102, in predict_brain_age_single_subject
    X = get_data(lh_thickness_file, rh_thickness_file, lh_area_file, rh_area_file, aseg_file)
  File "/code/baracus/predict.py", line 60, in get_data
    X["aseg"] = _vectorize_fs_tab(aseg_file)
  File "/code/baracus/predict.py", line 24, in _vectorize_fs_tab
    vectorized_data.shape)
AssertionError: /data/out/baracus/sub-103_ses-1/data/aseg shape does not look right: (1, 58)"
